AUDITKUBE_PATH=./auditkube
auditkube:
ifneq ($(wildcard ${AUDITKUBE_PATH}),)
	cd ${AUDITKUBE_PATH} && git fetch && git pull
else
	git clone https://github.com/opszero/auditkube.git ${AUDITKUBE_PATH}
endif

build: auditkube
		cd ${AUDITKUBE_PATH} && \
		AWS_REGION=$(shell aws configure get <%= KubernetesSetup.aws_profile %>.region) \
		AWS_ACCESS_KEY=$(shell aws configure get <%= KubernetesSetup.aws_profile %>.aws_access_key_id) \
		AWS_SECRET_KEY=$(shell aws configure get <%= KubernetesSetup.aws_profile %>.aws_secret_access_key) \
		$(MAKE) -e build
